version: '3.8'
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"  # Exponer el puerto de Prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml  # Archivo de configuración
      - ./alert_rules.yml:/etc/prometheus/alert_rules.yml  # Reglas de alerta
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin  # Contraseña de admin
    ports:
      - "3000:3000"  # Puerto para Grafana
    depends_on:
      - prometheus
    networks:
      - monitoring

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    ports:
      - "9093:9093"  # Puerto para Alertmanager
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml  # Configuración de Alertmanager
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge
